### ISSUE TITLE
upgrade futures-cpupool to a newer version

### ISSUE THREAD

**Issue by froydnj** [djg/audioipc-2#36]
`AudioIPC` threads take up a lot of stack space by default, and there can be a lot of them.  Newer versions of `futures-cpupool` support [setting the stack size](https://docs.rs/futures/0.2.0-alpha/futures/executor/struct.ThreadPoolBuilder.html#method.stack_size) for thread pools.  We should use a newer version of `futures-cpupool` so the stack size of `AudioIPC` threads can be limited somewhat.

**Comment by froydnj** [comment]
To be clear, `futures-cpupool` 0.1.18 would be fine (or any other version that supports the necessary call); upgrading to an alpha version is not required!

**Comment by djg** [comment]
Hi @froydnj, 

I originally used a more up-to-date version of `futures-cpupool` but had to roll back so as not to add multiple versions of crates to Gecko. (Rayon was using an older version futures-rs and it was there first so it won).

**Comment by froydnj** [comment]
> I originally used a more up-to-date version of futures-cpupool but had to roll back so as not to add multiple versions of crates to Gecko. (Rayon was using an older version futures-rs and it was there first so it won).

I don't understand this objection: there are multiple versions of many crates in Gecko already...

In any event, this is a solvable problem, either we can:

1. Upgrade `futures-cpupool` right now; or
2. Work through the dependency graph to upgrade `rayon`.

Looking at mozilla-central, though, it looks like there is only one version of `rayon` and it doesn't depend on `futures-cpupool`.  So maybe we can just do number 1, above?

**Comment by djg** [comment]
It's not an objection; I'm sorry you took it that way. I was just outlining a little history.

I'm updating to the new `futures-cpupool` now and plan to expose prefs in Gecko to control the number of threads in the pool and size of stack.

**Comment by froydnj** [comment]
> It's not an objection; I'm sorry you took it that way. I was just outlining a little history.

Ah, thank you for explaining the history.  Re-reading my comment, I see that it came off much snarkier than I should have written it; my apologies.

> I'm updating to the new futures-cpupool now and plan to expose prefs in Gecko to control the number of threads in the pool and size of stack.

Thank you!

**Comment by djg** [comment]
Closed by #37
