### ISSUE TITLE
musl requires padding for liblibc

### ISSUE THREAD

**Issue by anarchpenguin** [djg/audioipc-2#43]
From: Jory A. Pratt <anarchy@gentoo.org>

Musl requires pad1 for libc

diff --git a/media/audioipc/audioipc/src/cmsg.rs b/media/audioipc/audioipc/src/cmsg.rs
--- a/media/audioipc/audioipc/src/cmsg.rs
+++ b/media/audioipc/audioipc/src/cmsg.rs
@@ -105,16 +105,18 @@ impl ControlMsgBuilder {
             if cmsg.remaining_mut() < cmsg_len {
                 return Err(Error::NoSpace);
             }
 
             let cmsghdr = cmsghdr {
                 cmsg_len: cmsg_len as _,
                 cmsg_level: level,
                 cmsg_type: kind,
+		#[cfg(target_env = "musl")]
+		__pad1: 0,
             };
 
             let cmsghdr = unsafe {
                 slice::from_raw_parts(&cmsghdr as *const _ as *const _, mem::size_of::<cmsghdr>())
             };
             cmsg.put_slice(cmsghdr);
             let mut cmsg = try!(align_buf(cmsg));
             cmsg.put_slice(msg);

**Comment by kinetiknz** [comment]
Thanks for the patch.  I've moved `__pad1` after `cmsg_len`, since that's the order they're listed in the documentation: http://rust-lang.github.io/libc/x86_64-unknown-linux-musl/libc/struct.cmsghdr.html
