### ISSUE TITLE
adapt for tokio-uds 0.2.0

### ISSUE THREAD

**Issue by landryb** [djg/audioipc-2#46]
cf https://bugzilla.mozilla.org/show_bug.cgi?id=1467872

right now with uds 0.2.0 it fails to build:
```
    Compiling audioipc v0.2.4 (file:///home/landry/src/audioipc-2/audioipc)
error[E0061]: this function takes 2 parameters but 1 parameter was supplied
  --> audioipc/src/async.rs:62:34
   |
62 |         if let Async::NotReady = <UnixStream>::poll_read(self) {
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 parameters

error[E0308]: mismatched types
  --> audioipc/src/async.rs:62:16
   |
62 |         if let Async::NotReady = <UnixStream>::poll_read(self) {
   |                ^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `futures::Async`
  |
   = note: expected type `std::result::Result<futures::Async<usize>, std::io::Error>`
              found type `futures::Async<_>`

error[E0599]: no method named `need_read` found for type `&mut tokio_uds::UnixStream` in the current scope
   --> audioipc/src/async.rs:118:22
    |
118 |                 self.need_read();
    |                      ^^^^^^^^^

error[E0061]: this function takes 2 parameters but 1 parameter was supplied
   --> audioipc/src/async.rs:132:34
    |
132 |         if let Async::NotReady = <UnixStream>::poll_write(self) {
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 parameters

error[E0308]: mismatched types
   --> audioipc/src/async.rs:132:16
    |
132 |         if let Async::NotReady = <UnixStream>::poll_write(self) {
    |                ^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `futures::Async`
    |
    = note: expected type `std::result::Result<futures::Async<usize>, std::io::Error>`
               found type `futures::Async<_>`

error[E0599]: no method named `need_write` found for type `&mut tokio_uds::UnixStream` in the current scope
   --> audioipc/src/async.rs:153:22
    |
153 |                 self.need_write();
    |                      ^^^^^^^^^^

```

**Comment by kinetiknz** [comment]
It looks like tokio-uds will need additional changes before we can update to it.  `need_read` and `need_write` have been removed from `UnixStream` and the replacement `clear_read_ready` and `clear_write_ready` haven't been exposed publically.

`from_stream` has been renamed to `from_std`, but it also takes a different `Handle` type, so we may have to move all of our Tokio use to the newer version  to make progress on this.

**Comment by djg** [comment]
Does this require an update to version 0.2 of all the futures and tokio
crates?

**Comment by kinetiknz** [comment]
Fortunately it's not the big tokio/futures 0.2 change, just the earlier tokio reform work for 0.1.

It turns out there's a compat shim for tokio `Handle` types, so it's possible to convert the old-style tokio_core `Handle` into a new tokio_reactor `Handle` via `new_tokio_handle()`.

It seems like that's the only additional change necessary to compile, so I've pushed a branch to https://github.com/djg/audioipc-2/tree/tokio_uds_020.  Note that it does rely on a modified tokio_uds that reexports `clear_read_ready` and `clear_write_ready`.  `ipctest` doesn't complete with this branch, so there's still some fixes necessary somewhere.

**Comment by landryb** [comment]
i only see a single commit on the tokio_uds_020 branch.. is it the one that's supposed to build with tokio-uds 0.2.0 ? seems the same as the ctest branch.

As for reexporting clear_{read,write}_ready, how can this be handled ? fixed upstream in the merged tokio repo ?

**Comment by kinetiknz** [comment]
I have a working build using tokio 0.1 and tokio-uds 0.2 (with minor local changes) now.  Working on getting this merged.

**Comment by kinetiknz** [comment]
Done via #64.
