### ISSUE TITLE
musl patch from #43 doesn't work on big endian

### ISSUE THREAD

**Issue by awilfox** [djg/audioipc-2#52]
From musl's <bits/socket.h>:
```c
struct cmsghdr {
#if __BYTE_ORDER == __BIG_ENDIAN
        int __pad1;
        socklen_t cmsg_len;
#else
        socklen_t cmsg_len;
        int __pad1;
#endif
        int cmsg_level;
        int cmsg_type;
};
```

So, __pad1 needs to come before cmsg_len on BE targets.

**Comment by kinetiknz** [comment]
Thanks for fixing this upstream.  I'll close this since we rely on libc's definition and don't define cmsghdr locally.

**Comment by kinetiknz** [comment]
There was also this: https://bugzilla.mozilla.org/show_bug.cgi?id=1536613
